# Fichier e:\KPI_HOSTING - V2.1\config\normalization_maps.yaml

ngdt_server_map:
  name: name
  power_state: infos.power_state
  guest_OS: infos.guest_OS
  networks: networks
  env: env
  tier: tier
  app: app
  division: division
  role: role
  source: source
  tags: tags
  # Mappage des tags, basés sur le dictionnaire créé par la stratégie

oxya_server_map:
  name: name
  power_state: infos.power_state
  guest_OS: infos.guest_OS
  networks: networks
  env: env
  tier: tier
  app: app
  division: division
  role: role
  source: source
  tags: tags

csv_server_map:
  name: name
  power_state: power_state
  guest_OS: guest_OS
  networks: networks
  env: env
  tier: tier
  app: app
  division: division
  role: role
  source: source
  tags: tags
  ip_address: ip_address
  # Mappage des tags, basés sur le dictionnaire créé par la stratégie

aws_server_map:
  server_name: tags.Name
  instance_id: instance_id
  region: placement.availability_zone

# azure_server_map:
#   server_name: name
#   resource_group: resourceGroup
#   location: location

checkmk_server_map:
  server_name: title
  ip_address: extensions.attributes.ipaddress
  alias: extensions.effective_attributes.alias
  codeapp: extensions.attributes.tag_CodeApp
  folder: extensions.folder
  site: extensions.effective_attributes.site

glpi_server_map:
  server_name: "1"
  guest_OS: "45"
  appliances: "1210"
  ip_address: "905"
  all_ip_address: "126"

rapid7_server_map:
  server_name: hostname
  ip_address: ip
  is_installed: is_installed
  riskScore: riskScore
