/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/apm': RouteRecordInfo<'/apm', '/apm', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/integration': RouteRecordInfo<'/integration', '/integration', Record<never, never>, Record<never, never>>,
    '/inventory': RouteRecordInfo<'/inventory', '/inventory', Record<never, never>, Record<never, never>, '/inventory/agents' | '/inventory/api' | '/inventory/dashboard' | '/inventory/health' | '/inventory/websites'>,
    '/inventory/agents': RouteRecordInfo<'/inventory/agents', '/inventory/agents', Record<never, never>, Record<never, never>>,
    '/inventory/api': RouteRecordInfo<'/inventory/api', '/inventory/api', Record<never, never>, Record<never, never>>,
    '/inventory/dashboard': RouteRecordInfo<'/inventory/dashboard', '/inventory/dashboard', Record<never, never>, Record<never, never>>,
    '/inventory/health': RouteRecordInfo<'/inventory/health', '/inventory/health', Record<never, never>, Record<never, never>>,
    '/inventory/websites': RouteRecordInfo<'/inventory/websites', '/inventory/websites', Record<never, never>, Record<never, never>>,
    '/itcm': RouteRecordInfo<'/itcm', '/itcm', Record<never, never>, Record<never, never>>,
    '/itsm': RouteRecordInfo<'/itsm', '/itsm', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/tenant': RouteRecordInfo<'/tenant', '/tenant', Record<never, never>, Record<never, never>>,
  }
}
